---

- name: "2.3.1 | PATCH | Ensure telnet client is not installed"
  ansible.builtin.package:
      name: telnet
      state: absent
  when:
      - not rhel9cis_telnet_required
      - "'telnet' in ansible_facts.packages"
      - rhel9cis_rule_2_3_1
  tags:
      - level1-server
      - level1-workstation
      - patch
      - telnet
      - rule_2.3.1

- name: "2.3.2 | PATCH | Ensure LDAP client is not installed"
  ansible.builtin.package:
      name: openldap-clients
      state: absent
  when:
      - not rhel9cis_openldap_clients_required
      - "'openldap-clients' in ansible_facts.packages"
      - rhel9cis_rule_2_3_2
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ldap
      - rule_2.3.2

- name: "2.3.3 | PATCH | Ensure TFTP client is not installed"
  ansible.builtin.package:
      name: tftp
      state: absent
  when:
      - not rhel9cis_tftp_client
      - "'tftp' in ansible_facts.packages"
      - rhel9cis_rule_2_3_3
  tags:
      - level1-server
      - level1-workstation
      - patch
      - tftp
      - rule_2.3.3

- name: "2.3.4 | PATCH | Ensure FTP client is not installed"
  ansible.builtin.package:
      name: ftp
      state: absent
  when:
      - not rhel9cis_tftp_client
      - "'ftp' in ansible_facts.packages"
      - rhel9cis_rule_2_3_4
  tags:
      - level1-server
      - level1-workstation
      - patch
      - ftp
      - rule_2.3.4
