---

- name: "SECTION | 1.1.1.x | Disable unused filesystems"
  ansible.builtin.import_tasks:
    file: cis_1.1.1.x.yml

- name: "SECTION | 1.1.2.1.x | Configure /tmp"
  ansible.builtin.import_tasks:
    file: cis_1.1.2.1.x.yml

- name: "SECTION | 1.1.2.2.x | Configure /dev/shm"
  ansible.builtin.import_tasks:
    file: cis_1.1.2.2.x.yml

- name: "SECTION | 1.1.2.3.x | Configure /home"
  ansible.builtin.import_tasks:
    file: cis_1.1.2.3.x.yml

- name: "SECTION | 1.1.2.4.x | Configure /var"
  ansible.builtin.import_tasks:
    file: cis_1.1.2.4.x.yml

- name: "SECTION | 1.1.2.5.x | Configure /var/tmp"
  ansible.builtin.import_tasks:
    file: cis_1.1.2.5.x.yml

- name: "SECTION | 1.1.2.6.x | Configure /var/log"
  ansible.builtin.import_tasks:
    file: cis_1.1.2.6.x.yml

- name: "SECTION | 1.1.2.7.x | Configure /var/log/audit"
  ansible.builtin.import_tasks:
    file: cis_1.1.2.7.x.yml

- name: "SECTION | 1.2.1.x | Configure Package Repositories"
  ansible.builtin.import_tasks:
    file: cis_1.2.1.x.yml

- name: "SECTION | 1.2.2.x | Configure Package Updates"
  ansible.builtin.import_tasks:
    file: cis_1.2.2.x.yml

- name: "SECTION | 1.3.1 | Configure SELinux"
  ansible.builtin.import_tasks:
    file: cis_1.3.1.x.yml

- name: "SECTION | 1.4 | Configure Bootloader"
  ansible.builtin.import_tasks:
    file: cis_1.4.x.yml

- name: "SECTION | 1.5 | Additional Process Hardening"
  ansible.builtin.import_tasks:
    file: cis_1.5.x.yml

- name: "SECTION | 1.6 | Configure system wide crypto policy"
  ansible.builtin.import_tasks:
    file: cis_1.6.x.yml

- name: "SECTION | 1.7 | Command Line Warning Banners"
  ansible.builtin.import_tasks:
    file: cis_1.7.x.yml

- name: "SECTION | 1.8 | Gnome Display Manager"
  when: rhel10cis_display_manager == 'gdm'
  ansible.builtin.import_tasks:
    file: cis_1.8.x.yml
