---

- name: "4.1.2.1 | PATCH | Ensure audit log storage size is configured"
  ansible.builtin.lineinfile:
      path: /etc/audit/auditd.conf
      regexp: "^max_log_file( |=)"
      line: "max_log_file = {{ rhel9cis_max_log_file_size }}"
  notify: Restart auditd
  when:
      - rhel9cis_rule_4_1_2_1
  tags:
      - level2-server
      - level2-workstation
      - patch
      - auditd
      - rule_4.1.2.1

- name: "4.1.2.2 | PATCH | Ensure audit logs are not automatically deleted"
  ansible.builtin.lineinfile:
      path: /etc/audit/auditd.conf
      regexp: "^max_log_file_action"
      line: "max_log_file_action = {{ rhel9cis_auditd['max_log_file_action'] }}"
  notify: Restart auditd
  when:
      - rhel9cis_rule_4_1_2_2
  tags:
      - level2-server
      - level2-workstation
      - patch
      - auditd
      - rule_4.1.2.2

- name: "4.1.2.3 | PATCH | Ensure system is disabled when audit logs are full"
  ansible.builtin.lineinfile:
      path: /etc/audit/auditd.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
  notify: Restart auditd
  loop:
      - { regexp: '^admin_space_left_action', line: 'admin_space_left_action = {{ rhel9cis_auditd.admin_space_left_action }}' }
      - { regexp: '^action_mail_acct', line: 'action_mail_acct = {{ rhel9cis_auditd.action_mail_acct }}' }
      - { regexp: '^space_left_action', line: 'space_left_action = {{ rhel9cis_auditd.space_left_action }}' }
  when:
      - rhel9cis_rule_4_1_2_3
  tags:
      - level2-server
      - level2-workstation
      - patch
      - auditd
      - rule_4.1.2.3

- name: PATCH | Configure other keys for auditd.conf
  ansible.builtin.lineinfile:
      path: /etc/audit/auditd.conf
      regexp: "^{{ item }}( |=)"
      line: "{{ item }} = {{ rhel9cis_auditd_extra_conf[item] }}"
  loop: "{{ rhel9cis_auditd_extra_conf.keys() }}"
  notify: Restart auditd
  when:
      - rhel9cis_auditd_extra_conf.keys() | length > 0
  tags:
      - level2-server
      - level2-workstation
      - patch
      - auditd
