---

- name: "SECTION | 4.1 | Configure System Accounting (auditd)"
  ansible.builtin.import_tasks: cis_4.1.1.x.yml
  when:
      - not system_is_container

- name: "SECTION | 4.1.2 | Configure Data Retention"
  ansible.builtin.import_tasks: cis_4.1.2.x.yml

- name: "SECTION | 4.1.3 | Configure Auditd rules"
  ansible.builtin.import_tasks: cis_4.1.3.x.yml

- name: "SECTION | 4.1.4 | Configure Audit files"
  ansible.builtin.import_tasks: cis_4.1.4.x.yml

- name: "SECTION | 4.2 | Configure Logging"
  ansible.builtin.import_tasks: cis_4.2.1.x.yml
  when: rhel9cis_syslog == 'rsyslog'

- name: "SECTION | 4.2.2 | Configure journald"
  ansible.builtin.import_tasks: cis_4.2.2.x.yml
  when: rhel9cis_syslog == 'journald'

- name: "SECTION | 4.2.3 | Configure logile perms"
  ansible.builtin.import_tasks: cis_4.2.3.yml

- name: "SECTION | 4.3 | Configure logrotate"
  ansible.builtin.import_tasks: cis_4.3.yml
